api: none
api-version: "1.15"
name: RecompensesVote
version: "1.1"
author: PoC4 / Fox
main: me.lataverne.recompensesvote.Main
commands:
  selectvotereward:
    description: select vote reward
    permission: recompensesvote.selectvotereward
    default: op
  item:
    description: give item
    permission: recompensesvote.item
    default: op