api: none
api-version: "1.14"
name: RecompensesVote
version: "1.0"
author: PoC4
main: fr.neolithic.recompensesvote.Main
commands:
  test:
    description: test
    permission: recompensesvote.test
    default: op
  selectvotereward:
    description: select vote reward
    permission: recompensesvote.selectvotereward
    default: op
  item:
    description: give item
    permission: recompensesvote.item
    default: op